[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Keto Friendly Recipes"
  url = "recipe/keto-friendly-list/"
  weight = -109

[[main]]
  name = "Recipes"
  url = "recipe/"
  weight = -109

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/dmcgaa/"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"